//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import axios, { AxiosError } from 'axios'
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios'
import { ServiceProxyBase } from './ServiceProxyBase'

export class AppServiceProxy extends ServiceProxyBase {
  protected instance: AxiosInstance
  protected baseUrl: string
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined

  constructor(baseUrl?: string, instance?: AxiosInstance) {
    super()

    this.instance = instance || axios.create()

    this.baseUrl = baseUrl ?? ''
  }

  appController_getHello(cancelToken?: CancelToken): Promise<void> {
    let url_ = this.baseUrl + '/api'
    url_ = url_.replace(/[?&]$/, '')

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {},
      cancelToken,
    }

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.instance.request(transformedOptions_)
      })
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.transformResult(url_, _response, (_response: AxiosResponse) =>
          this.processAppController_getHello(_response),
        )
      })
  }

  protected processAppController_getHello(response: AxiosResponse): Promise<void> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      return Promise.resolve<void>(null as any)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException('An unexpected server error occurred.', status, _responseText, _headers)
    }
    return Promise.resolve<void>(null as any)
  }
}

export class DevicesServiceProxy extends ServiceProxyBase {
  protected instance: AxiosInstance
  protected baseUrl: string
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined

  constructor(baseUrl?: string, instance?: AxiosInstance) {
    super()

    this.instance = instance || axios.create()

    this.baseUrl = baseUrl ?? ''
  }

  /**
   * Create a new device
   */
  devicesController_create(body: CreateDeviceDto, cancelToken?: CancelToken): Promise<Device> {
    let url_ = this.baseUrl + '/api/devices'
    url_ = url_.replace(/[?&]$/, '')

    const content_ = JSON.stringify(body)

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      cancelToken,
    }

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.instance.request(transformedOptions_)
      })
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.transformResult(url_, _response, (_response: AxiosResponse) =>
          this.processDevicesController_create(_response),
        )
      })
  }

  protected processDevicesController_create(response: AxiosResponse): Promise<Device> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      let result200: any = null
      let resultData200 = _responseText
      result200 = Device.fromJS(resultData200)
      return Promise.resolve<Device>(result200)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException('An unexpected server error occurred.', status, _responseText, _headers)
    }
    return Promise.resolve<Device>(null as any)
  }

  /**
   * Get all devices
   */
  devicesController_findAll(cancelToken?: CancelToken): Promise<Device[]> {
    let url_ = this.baseUrl + '/api/devices'
    url_ = url_.replace(/[?&]$/, '')

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {
        Accept: 'application/json',
      },
      cancelToken,
    }

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.instance.request(transformedOptions_)
      })
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.transformResult(url_, _response, (_response: AxiosResponse) =>
          this.processDevicesController_findAll(_response),
        )
      })
  }

  protected processDevicesController_findAll(response: AxiosResponse): Promise<Device[]> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      let result200: any = null
      let resultData200 = _responseText
      if (Array.isArray(resultData200)) {
        result200 = [] as any
        for (let item of resultData200) result200!.push(Device.fromJS(item))
      } else {
        result200 = null as any
      }
      return Promise.resolve<Device[]>(result200)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException('An unexpected server error occurred.', status, _responseText, _headers)
    }
    return Promise.resolve<Device[]>(null as any)
  }

  /**
   * Check online status of all devices
   */
  devicesController_checkStatus(cancelToken?: CancelToken): Promise<DeviceStatusDto[]> {
    let url_ = this.baseUrl + '/api/devices/status'
    url_ = url_.replace(/[?&]$/, '')

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {
        Accept: 'application/json',
      },
      cancelToken,
    }

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.instance.request(transformedOptions_)
      })
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.transformResult(url_, _response, (_response: AxiosResponse) =>
          this.processDevicesController_checkStatus(_response),
        )
      })
  }

  protected processDevicesController_checkStatus(
    response: AxiosResponse,
  ): Promise<DeviceStatusDto[]> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      let result200: any = null
      let resultData200 = _responseText
      if (Array.isArray(resultData200)) {
        result200 = [] as any
        for (let item of resultData200) result200!.push(DeviceStatusDto.fromJS(item))
      } else {
        result200 = null as any
      }
      return Promise.resolve<DeviceStatusDto[]>(result200)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException('An unexpected server error occurred.', status, _responseText, _headers)
    }
    return Promise.resolve<DeviceStatusDto[]>(null as any)
  }

  /**
   * Get a device by ID
   */
  devicesController_findOne(id: number, cancelToken?: CancelToken): Promise<Device> {
    let url_ = this.baseUrl + '/api/devices/{id}'
    if (id === undefined || id === null)
      throw new globalThis.Error("The parameter 'id' must be defined.")
    url_ = url_.replace('{id}', encodeURIComponent('' + id))
    url_ = url_.replace(/[?&]$/, '')

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {
        Accept: 'application/json',
      },
      cancelToken,
    }

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.instance.request(transformedOptions_)
      })
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.transformResult(url_, _response, (_response: AxiosResponse) =>
          this.processDevicesController_findOne(_response),
        )
      })
  }

  protected processDevicesController_findOne(response: AxiosResponse): Promise<Device> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      let result200: any = null
      let resultData200 = _responseText
      result200 = Device.fromJS(resultData200)
      return Promise.resolve<Device>(result200)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException('An unexpected server error occurred.', status, _responseText, _headers)
    }
    return Promise.resolve<Device>(null as any)
  }

  /**
   * Update a device
   */
  devicesController_update(
    id: number,
    body: UpdateDeviceDto,
    cancelToken?: CancelToken,
  ): Promise<Device> {
    let url_ = this.baseUrl + '/api/devices/{id}'
    if (id === undefined || id === null)
      throw new globalThis.Error("The parameter 'id' must be defined.")
    url_ = url_.replace('{id}', encodeURIComponent('' + id))
    url_ = url_.replace(/[?&]$/, '')

    const content_ = JSON.stringify(body)

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'PATCH',
      url: url_,
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      cancelToken,
    }

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.instance.request(transformedOptions_)
      })
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.transformResult(url_, _response, (_response: AxiosResponse) =>
          this.processDevicesController_update(_response),
        )
      })
  }

  protected processDevicesController_update(response: AxiosResponse): Promise<Device> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      let result200: any = null
      let resultData200 = _responseText
      result200 = Device.fromJS(resultData200)
      return Promise.resolve<Device>(result200)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException('An unexpected server error occurred.', status, _responseText, _headers)
    }
    return Promise.resolve<Device>(null as any)
  }

  /**
   * Delete a device
   * @return Device deleted successfully
   */
  devicesController_remove(id: number, cancelToken?: CancelToken): Promise<void> {
    let url_ = this.baseUrl + '/api/devices/{id}'
    if (id === undefined || id === null)
      throw new globalThis.Error("The parameter 'id' must be defined.")
    url_ = url_.replace('{id}', encodeURIComponent('' + id))
    url_ = url_.replace(/[?&]$/, '')

    let options_: AxiosRequestConfig = {
      method: 'DELETE',
      url: url_,
      headers: {},
      cancelToken,
    }

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.instance.request(transformedOptions_)
      })
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.transformResult(url_, _response, (_response: AxiosResponse) =>
          this.processDevicesController_remove(_response),
        )
      })
  }

  protected processDevicesController_remove(response: AxiosResponse): Promise<void> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      return Promise.resolve<void>(null as any)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException('An unexpected server error occurred.', status, _responseText, _headers)
    }
    return Promise.resolve<void>(null as any)
  }
}

export class WolServiceProxy extends ServiceProxyBase {
  protected instance: AxiosInstance
  protected baseUrl: string
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined

  constructor(baseUrl?: string, instance?: AxiosInstance) {
    super()

    this.instance = instance || axios.create()

    this.baseUrl = baseUrl ?? ''
  }

  /**
   * Send WOL magic packet to a device
   * @return Magic packet sent successfully
   */
  wolController_wake(body: WakeDeviceDto, cancelToken?: CancelToken): Promise<void> {
    let url_ = this.baseUrl + '/api/wol'
    url_ = url_.replace(/[?&]$/, '')

    const content_ = JSON.stringify(body)

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'Content-Type': 'application/json',
      },
      cancelToken,
    }

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.instance.request(transformedOptions_)
      })
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response
        } else {
          throw _error
        }
      })
      .then((_response: AxiosResponse) => {
        return this.transformResult(url_, _response, (_response: AxiosResponse) =>
          this.processWolController_wake(_response),
        )
      })
  }

  protected processWolController_wake(response: AxiosResponse): Promise<void> {
    const status = response.status
    let _headers: any = {}
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k]
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data
      return Promise.resolve<void>(null as any)
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data
      return throwException('An unexpected server error occurred.', status, _responseText, _headers)
    }
    return Promise.resolve<void>(null as any)
  }
}

export class CreateDeviceDto implements ICreateDeviceDto {
  /** The name of the device */
  name!: string
  /** The IP address of the device */
  ipAddress!: string
  /** The MAC address of the device */
  macAddress!: string
  /** Optional notes about the device */
  notes?: string;

  [key: string]: any

  constructor(data?: ICreateDeviceDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) (this as any)[property] = (data as any)[property]
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      for (var property in _data) {
        if (_data.hasOwnProperty(property)) this[property] = _data[property]
      }
      this.name = _data['name']
      this.ipAddress = _data['ipAddress']
      this.macAddress = _data['macAddress']
      this.notes = _data['notes']
    }
  }

  static fromJS(data: any): CreateDeviceDto {
    data = typeof data === 'object' ? data : {}
    let result = new CreateDeviceDto()
    result.init(data)
    return result
  }

  toJSON(data?: any) {
    data = typeof data === 'object' ? data : {}
    for (var property in this) {
      if (this.hasOwnProperty(property)) data[property] = this[property]
    }
    data['name'] = this.name
    data['ipAddress'] = this.ipAddress
    data['macAddress'] = this.macAddress
    data['notes'] = this.notes
    return data
  }
}

export interface ICreateDeviceDto {
  /** The name of the device */
  name: string
  /** The IP address of the device */
  ipAddress: string
  /** The MAC address of the device */
  macAddress: string
  /** Optional notes about the device */
  notes?: string

  [key: string]: any
}

export class Device implements IDevice {
  id!: number
  name!: string
  ipAddress!: string
  macAddress!: string
  notes?: string;

  [key: string]: any

  constructor(data?: IDevice) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) (this as any)[property] = (data as any)[property]
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      for (var property in _data) {
        if (_data.hasOwnProperty(property)) this[property] = _data[property]
      }
      this.id = _data['id']
      this.name = _data['name']
      this.ipAddress = _data['ipAddress']
      this.macAddress = _data['macAddress']
      this.notes = _data['notes']
    }
  }

  static fromJS(data: any): Device {
    data = typeof data === 'object' ? data : {}
    let result = new Device()
    result.init(data)
    return result
  }

  toJSON(data?: any) {
    data = typeof data === 'object' ? data : {}
    for (var property in this) {
      if (this.hasOwnProperty(property)) data[property] = this[property]
    }
    data['id'] = this.id
    data['name'] = this.name
    data['ipAddress'] = this.ipAddress
    data['macAddress'] = this.macAddress
    data['notes'] = this.notes
    return data
  }
}

export interface IDevice {
  id: number
  name: string
  ipAddress: string
  macAddress: string
  notes?: string

  [key: string]: any
}

export class DeviceStatusDto implements IDeviceStatusDto {
  /** The ID of the device */
  id!: number
  /** Whether the device is online */
  isOnline!: boolean;

  [key: string]: any

  constructor(data?: IDeviceStatusDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) (this as any)[property] = (data as any)[property]
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      for (var property in _data) {
        if (_data.hasOwnProperty(property)) this[property] = _data[property]
      }
      this.id = _data['id']
      this.isOnline = _data['isOnline']
    }
  }

  static fromJS(data: any): DeviceStatusDto {
    data = typeof data === 'object' ? data : {}
    let result = new DeviceStatusDto()
    result.init(data)
    return result
  }

  toJSON(data?: any) {
    data = typeof data === 'object' ? data : {}
    for (var property in this) {
      if (this.hasOwnProperty(property)) data[property] = this[property]
    }
    data['id'] = this.id
    data['isOnline'] = this.isOnline
    return data
  }
}

export interface IDeviceStatusDto {
  /** The ID of the device */
  id: number
  /** Whether the device is online */
  isOnline: boolean

  [key: string]: any
}

export class UpdateDeviceDto implements IUpdateDeviceDto {
  [key: string]: any

  constructor(data?: IUpdateDeviceDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) (this as any)[property] = (data as any)[property]
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      for (var property in _data) {
        if (_data.hasOwnProperty(property)) this[property] = _data[property]
      }
    }
  }

  static fromJS(data: any): UpdateDeviceDto {
    data = typeof data === 'object' ? data : {}
    let result = new UpdateDeviceDto()
    result.init(data)
    return result
  }

  toJSON(data?: any) {
    data = typeof data === 'object' ? data : {}
    for (var property in this) {
      if (this.hasOwnProperty(property)) data[property] = this[property]
    }
    return data
  }
}

export interface IUpdateDeviceDto {
  [key: string]: any
}

export class WakeDeviceDto implements IWakeDeviceDto {
  [key: string]: any

  constructor(data?: IWakeDeviceDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property)) (this as any)[property] = (data as any)[property]
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      for (var property in _data) {
        if (_data.hasOwnProperty(property)) this[property] = _data[property]
      }
    }
  }

  static fromJS(data: any): WakeDeviceDto {
    data = typeof data === 'object' ? data : {}
    let result = new WakeDeviceDto()
    result.init(data)
    return result
  }

  toJSON(data?: any) {
    data = typeof data === 'object' ? data : {}
    for (var property in this) {
      if (this.hasOwnProperty(property)) data[property] = this[property]
    }
    return data
  }
}

export interface IWakeDeviceDto {
  [key: string]: any
}

export class ApiException extends Error {
  override message: string
  status: number
  response: string
  headers: { [key: string]: any }
  result: any

  constructor(
    message: string,
    status: number,
    response: string,
    headers: { [key: string]: any },
    result: any,
  ) {
    super()

    this.message = message
    this.status = status
    this.response = response
    this.headers = headers
    this.result = result
  }

  protected isApiException = true

  static isApiException(obj: any): obj is ApiException {
    return obj.isApiException === true
  }
}

function throwException(
  message: string,
  status: number,
  response: string,
  headers: { [key: string]: any },
  result?: any,
): any {
  if (result !== null && result !== undefined) throw result
  else throw new ApiException(message, status, response, headers, null)
}

function isAxiosError(obj: any): obj is AxiosError {
  return obj && obj.isAxiosError === true
}
